# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - IntelliTect.TestTools.Data/*

variables:
  version: '0.1.0'

pool:
  vmImage: 'windows-latest'

steps:

- task: NuGetToolInstaller@0
  displayName: 'Use latest NuGet'

- task: NuGetCommand@2
  displayName: 'NuGet Restore'
  inputs:
    command: 'restore'
    restoreSolution: '**/IntelliTect.TestTools.Data.sln'
    feedsToUse: 'select'

- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '**/IntelliTect.TestTools.Data.sln'
    clean: true
    configuration: 'Release'
    msbuildArgs: '/p:Version=$(version)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/IntelliTect.TestTools.Data.Tests.csproj'

- task: PowerShell@2
  displayName: 'dotnet pack'
  inputs:
    targetType: 'inline'
    script: dotnet pack --no-build -p:Version="$(version)-ci-$(Build.BuildId)" -o $(Build.ArtifactStagingDirectory)
    pwsh: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'